// Open public-domain country centroid coordinates (lat, lng).
export const COUNTRIES = [
  { code: 'US', name: 'United States', lat: 38.0, lng: -97.0 },
  { code: 'CN', name: 'China', lat: 35.8, lng: 104.1 },
  { code: 'RU', name: 'Russia', lat: 61.5, lng: 105.3 },
  { code: 'DE', name: 'Germany', lat: 51.1, lng: 10.4 },
  { code: 'GB', name: 'United Kingdom', lat: 55.3, lng: -3.4 },
  { code: 'FR', name: 'France', lat: 46.2, lng: 2.2 },
  { code: 'BR', name: 'Brazil', lat: -14.2, lng: -51.9 },
  { code: 'IN', name: 'India', lat: 20.5, lng: 78.9 },
  { code: 'JP', name: 'Japan', lat: 36.2, lng: 138.2 },
  { code: 'KR', name: 'South Korea', lat: 35.9, lng: 127.7 },
  { code: 'NL', name: 'Netherlands', lat: 52.1, lng: 5.2 },
  { code: 'CA', name: 'Canada', lat: 56.1, lng: -106.3 },
  { code: 'AU', name: 'Australia', lat: -25.2, lng: 133.7 },
  { code: 'IR', name: 'Iran', lat: 32.4, lng: 53.6 },
  { code: 'UA', name: 'Ukraine', lat: 48.3, lng: 31.1 },
  { code: 'VN', name: 'Vietnam', lat: 14.0, lng: 108.2 },
  { code: 'ID', name: 'Indonesia', lat: -0.7, lng: 113.9 },
  { code: 'TR', name: 'Turkey', lat: 38.9, lng: 35.2 },
  { code: 'SG', name: 'Singapore', lat: 1.3, lng: 103.8 },
  { code: 'ZA', name: 'South Africa', lat: -30.5, lng: 22.9 },
  { code: 'MX', name: 'Mexico', lat: 23.6, lng: -102.5 },
  { code: 'IT', name: 'Italy', lat: 41.8, lng: 12.5 },
  { code: 'ES', name: 'Spain', lat: 40.4, lng: -3.7 },
  { code: 'PL', name: 'Poland', lat: 51.9, lng: 19.1 },
  { code: 'SE', name: 'Sweden', lat: 60.1, lng: 18.6 },
  { code: 'HK', name: 'Hong Kong', lat: 22.3, lng: 114.1 },
  { code: 'TW', name: 'Taiwan', lat: 23.7, lng: 120.9 },
  { code: 'TH', name: 'Thailand', lat: 15.8, lng: 100.9 },
  { code: 'AE', name: 'United Arab Emirates', lat: 23.4, lng: 53.8 },
  { code: 'SA', name: 'Saudi Arabia', lat: 23.9, lng: 45.1 },
] as const;

export const ATTACK_TYPES = [
  'Web Attackers',
  'DDoS Attackers',
  'Intruders',
  'Scanners',
  'Anonymizers',
] as const;
